#!/bin/sh

# Generates element-desktop theme

. $HOME/.cache/wal/colors.sh

# Ensure that the Labs feature is on
cat $HOME/.config/Element/config_old.json | jq \
'del(.showLabsSettings)' | \
jq \
'. += {"showLabsSettings": true}' | \

# Remove older Wal theme
jq \
'del(.settingDefaults.custom_themes[] | select(.name == "Wal"))' | \

# Add new Wal theme
jq \
'.settingDefaults.custom_themes += [{
            "name": "Wal",
            "is_dark": true,
            "colors": {
                "accent-color": "'"$foreground"'",
                "accent": "'"$foreground"'",
                "primary-color": "'"$color4"'",
                "warning-color": "'"$color1"'",
                "alert": "'"$color1"'",
                "sidebar-color": "'"$background"'",
                "roomlist-background-color": "'"$color1"'",
                "roomlist-text-color": "'"$foreground"'",
                "roomlist-text-secondary-color": "'"$color9"'",
                "roomlist-highlights-color": "'"$color8"'",
                "roomlist-separator-color": "'"$color5"'",
                "timeline-background-color": "'"$background"'",
                "timeline-text-color": "'"$foreground"'",
                "timeline-text-secondary-color": "'"$foreground"'",
                "timeline-highlights-color": "'"$color1"'",
                "username-colors": ["'"$color0"'", "'"$color1"'", "'"$color2"'",
                "'"$color3"'", "'"$color4"'", "'"$color5"'", "'"$color6"'",
                "'"$color7"'"],
                "avatar-background-colors": ["'"$color3"'", "'"$color4"'",
                "'"$color5"'"],
                "reaction-row-button-selected-bg-color": "'"$color4"'",
                "menu-selected-color": "'"$color4"'",
                "focus-bg-color": "'"$color4"'",
                "room-highlight-color": "'"$color4"'",
                "other-user-pill-bg-color": "'"$color4"'",
                "togglesw-off-color": "'"$color4"'",
                "secondary-content": "'"$foreground"'",
                "tertiary-content": "'"$foreground"'"
            }
}]'
